spring.application.name=CommercePJT

# H2 Database
spring.datasource.url=jdbc:h2:mem:commercedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Session (24h) + HttpOnly cookie
server.servlet.session.timeout=24h
server.servlet.session.cookie.http-only=true

# 테스트전용데이터
spring.jpa.defer-datasource-initialization=true